import type { Locale } from "@/lib/i18n";
import type { Allergen, Badge, Highlight } from "@/lib/types";

export const allergenLabels: Record<Locale, Record<Allergen, string>> = {
  tr: {
    gluten: "Gluten",
    laktoz: "Laktoz",
    yumurta: "Yumurta",
    findik_fistik: "Fındık/Fıstık",
    yer_fistigi: "Yer fıstığı",
    soya: "Soya",
    balik: "Balık",
    kabuklu_deniz_urunu: "Kabuklu deniz ürünü",
    susam: "Susam",
    hardal: "Hardal",
    kereviz: "Kereviz",
    sulfit: "Sülfit",
  },
  en: {
    gluten: "Gluten",
    laktoz: "Lactose",
    yumurta: "Egg",
    findik_fistik: "Nuts",
    yer_fistigi: "Peanut",
    soya: "Soy",
    balik: "Fish",
    kabuklu_deniz_urunu: "Shellfish",
    susam: "Sesame",
    hardal: "Mustard",
    kereviz: "Celery",
    sulfit: "Sulphites",
  },
  de: {
    gluten: "Gluten",
    laktoz: "Laktose",
    yumurta: "Ei",
    findik_fistik: "Schalenfrüchte",
    yer_fistigi: "Erdnuss",
    soya: "Soja",
    balik: "Fisch",
    kabuklu_deniz_urunu: "Krebstiere",
    susam: "Sesam",
    hardal: "Senf",
    kereviz: "Sellerie",
    sulfit: "Sulfite",
  },
  ar: {
    gluten: "الغلوتين",
    laktoz: "اللاكتوز",
    yumurta: "البيض",
    findik_fistik: "المكسرات",
    yer_fistigi: "الفول السوداني",
    soya: "الصويا",
    balik: "السمك",
    kabuklu_deniz_urunu: "المحار",
    susam: "السمسم",
    hardal: "الخردل",
    kereviz: "الكرفس",
    sulfit: "الكبريتيت",
  },
  fr: {
    gluten: "Gluten",
    laktoz: "Lactose",
    yumurta: "Œuf",
    findik_fistik: "Fruits à coque",
    yer_fistigi: "Arachide",
    soya: "Soja",
    balik: "Poisson",
    kabuklu_deniz_urunu: "Crustacés",
    susam: "Sésame",
    hardal: "Moutarde",
    kereviz: "Céleri",
    sulfit: "Sulfites",
  },
  es: {
    gluten: "Gluten",
    laktoz: "Lactosa",
    yumurta: "Huevo",
    findik_fistik: "Frutos de cáscara",
    yer_fistigi: "Cacahuete",
    soya: "Soja",
    balik: "Pescado",
    kabuklu_deniz_urunu: "Marisco",
    susam: "Sésamo",
    hardal: "Mostaza",
    kereviz: "Apio",
    sulfit: "Sulfitos",
  },
  it: {
    gluten: "Glutine",
    laktoz: "Lattosio",
    yumurta: "Uova",
    findik_fistik: "Frutta a guscio",
    yer_fistigi: "Arachidi",
    soya: "Soia",
    balik: "Pesce",
    kabuklu_deniz_urunu: "Crostacei",
    susam: "Sesamo",
    hardal: "Senape",
    kereviz: "Sedano",
    sulfit: "Solfiti",
  },
  ru: {
    gluten: "Глютен",
    laktoz: "Лактоза",
    yumurta: "Яйцо",
    findik_fistik: "Орехи",
    yer_fistigi: "Арахис",
    soya: "Соя",
    balik: "Рыба",
    kabuklu_deniz_urunu: "Моллюски",
    susam: "Кунжут",
    hardal: "Горчица",
    kereviz: "Сельдерей",
    sulfit: "Сульфиты",
  },
};

export const badgeLabels: Record<Locale, Record<Badge, string>> = {
  tr: {
    yeni: "Yeni",
    sefin_onerisi: "Şefin önerisi",
    populer: "Popüler",
    vejetaryen: "Vejetaryen",
    vegan: "Vegan",
    aci: "Acılı",
    glutensiz: "Glutensiz",
  },
  en: {
    yeni: "New",
    sefin_onerisi: "Chef's pick",
    populer: "Popular",
    vejetaryen: "Vegetarian",
    vegan: "Vegan",
    aci: "Spicy",
    glutensiz: "Gluten-free",
  },
  de: {
    yeni: "Neu",
    sefin_onerisi: "Empfehlung des Küchenchefs",
    populer: "Beliebt",
    vejetaryen: "Vegetarisch",
    vegan: "Vegan",
    aci: "Scharf",
    glutensiz: "Glutenfrei",
  },
  ar: {
    yeni: "جديد",
    sefin_onerisi: "توصية الشيف",
    populer: "الأكثر طلبًا",
    vejetaryen: "نباتي",
    vegan: "نباتي صرف",
    aci: "حار",
    glutensiz: "خالٍ من الغلوتين",
  },
  fr: {
    yeni: "Nouveau",
    sefin_onerisi: "Suggestion du chef",
    populer: "Populaire",
    vejetaryen: "Végétarien",
    vegan: "Végan",
    aci: "Épicé",
    glutensiz: "Sans gluten",
  },
  es: {
    yeni: "Nuevo",
    sefin_onerisi: "Recomendación del chef",
    populer: "Popular",
    vejetaryen: "Vegetariano",
    vegan: "Vegano",
    aci: "Picante",
    glutensiz: "Sin gluten",
  },
  it: {
    yeni: "Novità",
    sefin_onerisi: "Consigliato dallo chef",
    populer: "Popolare",
    vejetaryen: "Vegetariano",
    vegan: "Vegano",
    aci: "Piccante",
    glutensiz: "Senza glutine",
  },
  ru: {
    yeni: "Новинка",
    sefin_onerisi: "Выбор шефа",
    populer: "Популярное",
    vejetaryen: "Вегетарианское",
    vegan: "Веганское",
    aci: "Острое",
    glutensiz: "Без глютена",
  },
};

export const highlightLabels: Record<Locale, Record<Highlight, string>> = {
  tr: {
    wifi: "Ücretsiz Wi-Fi",
    vale: "Vale Hizmeti",
    otopark: "Otopark",
    cocuk_oyun_alani: "Çocuk Oyun Alanı",
    evcil_hayvan_dostu: "Evcil Hayvan Dostu",
    teras: "Teras",
    canli_muzik: "Canlı Müzik",
    rezervasyon: "Rezervasyon",
    kredi_karti: "Kredi Kartı",
    engelli_erisimi: "Engelli Erişimi",
    sigara_alani: "Sigara Alanı",
    kahvalti: "Kahvaltı",
  },
  en: {
    wifi: "Free Wi-Fi",
    vale: "Valet Service",
    otopark: "Parking",
    cocuk_oyun_alani: "Kids' Play Area",
    evcil_hayvan_dostu: "Pet Friendly",
    teras: "Terrace",
    canli_muzik: "Live Music",
    rezervasyon: "Reservations",
    kredi_karti: "Credit Card",
    engelli_erisimi: "Accessible",
    sigara_alani: "Smoking Area",
    kahvalti: "Breakfast",
  },
  de: {
    wifi: "Kostenloses WLAN",
    vale: "Parkservice",
    otopark: "Parkplatz",
    cocuk_oyun_alani: "Kinderspielbereich",
    evcil_hayvan_dostu: "Haustierfreundlich",
    teras: "Terrasse",
    canli_muzik: "Livemusik",
    rezervasyon: "Reservierung",
    kredi_karti: "Kartenzahlung",
    engelli_erisimi: "Barrierefrei",
    sigara_alani: "Raucherbereich",
    kahvalti: "Frühstück",
  },
  ar: {
    wifi: "واي فاي مجاني",
    vale: "خدمة صف السيارات",
    otopark: "موقف سيارات",
    cocuk_oyun_alani: "منطقة ألعاب أطفال",
    evcil_hayvan_dostu: "يسمح بالحيوانات الأليفة",
    teras: "تراس",
    canli_muzik: "موسيقى حية",
    rezervasyon: "حجز مسبق",
    kredi_karti: "بطاقة ائتمان",
    engelli_erisimi: "دخول لذوي الاحتياجات",
    sigara_alani: "منطقة تدخين",
    kahvalti: "إفطار",
  },
  fr: {
    wifi: "Wi-Fi gratuit",
    vale: "Voiturier",
    otopark: "Parking",
    cocuk_oyun_alani: "Espace de jeux pour enfants",
    evcil_hayvan_dostu: "Animaux acceptés",
    teras: "Terrasse",
    canli_muzik: "Musique live",
    rezervasyon: "Réservation",
    kredi_karti: "Carte bancaire",
    engelli_erisimi: "Accessible PMR",
    sigara_alani: "Espace fumeurs",
    kahvalti: "Petit-déjeuner",
  },
  es: {
    wifi: "Wi-Fi gratis",
    vale: "Aparcacoches",
    otopark: "Aparcamiento",
    cocuk_oyun_alani: "Zona de juegos infantil",
    evcil_hayvan_dostu: "Se admiten mascotas",
    teras: "Terraza",
    canli_muzik: "Música en directo",
    rezervasyon: "Reservas",
    kredi_karti: "Pago con tarjeta",
    engelli_erisimi: "Accesible",
    sigara_alani: "Zona de fumadores",
    kahvalti: "Desayuno",
  },
  it: {
    wifi: "Wi-Fi gratuito",
    vale: "Parcheggiatore",
    otopark: "Parcheggio",
    cocuk_oyun_alani: "Area giochi per bambini",
    evcil_hayvan_dostu: "Animali ammessi",
    teras: "Terrazza",
    canli_muzik: "Musica dal vivo",
    rezervasyon: "Prenotazioni",
    kredi_karti: "Pagamento con carta",
    engelli_erisimi: "Accessibile",
    sigara_alani: "Area fumatori",
    kahvalti: "Colazione",
  },
  ru: {
    wifi: "Бесплатный Wi-Fi",
    vale: "Услуги парковщика",
    otopark: "Парковка",
    cocuk_oyun_alani: "Детская площадка",
    evcil_hayvan_dostu: "Можно с животными",
    teras: "Терраса",
    canli_muzik: "Живая музыка",
    rezervasyon: "Бронирование",
    kredi_karti: "Оплата картой",
    engelli_erisimi: "Доступная среда",
    sigara_alani: "Зона для курения",
    kahvalti: "Завтрак",
  },
};
